# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27733324a7983faa0e59dcab48ee138243e3aa0e98502a73e3cff5726f6e5853e2a9683afd1cec174dfd7e5c8b0f3009e6a9a7c739254645adbdef9917e556ff

test:
  secret_key_base: e18375ed85fc9d70899aac5557a68f782bf3276ea4d85968886ecfa9288718b0c2509faf3c4c420c0f29f86470b99a1c671f48e37c4b2cdaf3d0b1b63046f6cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
